[Config General]
description = General Network Configurations
network = ThesisA

sim-time-limit = 300s  # Χρονικό όριο προσομοίωσης
*.scalar-recording = true  # Καταγραφή στατιστικών
*.vector-recording = true 

*.routingTableRecorder.enabled = true 

# ---------------------- ΔΙΚΤΥΑΚΕΣ ΡΥΘΜΙΣΕΙΣ ----------------------
*.configurator.addStaticRoutes = false
**.netmaskRoutes = ""
**.arp.typename = "GlobalArp"
*.**.**.bitrate = 24Mbps
*.configurator.optimizeRoutes = true
*.**.forwarding = true

# ---------------------- ΕΜΒΕΛΕΙΑ ΣΗΜΑΤΩΝ ----------------------
*.Building*.wlan[0].radio.transmitter.power = 2mW

*.drone*.wlan[0].radio.transmitter.power = 3mW

*.BuildingA.wlan[0].radio.displayInterferenceRange = true

# ------------- ΜΟΝΤΕΛΟ ΑΠΩΛΕΙΩΝ ΣΗΜΑΤΟΣ ------------
*.radioMedium.pathLoss.typename = "LogNormalShadowing"
*.radioMedium.pathLoss.systemLoss = 5dB

#----------------- ANTENNA GAIN -----------------------
*.**.wlan[0].radio.antenna.typename = "ConstantGainAntenna"
*.**.wlan[0].radio.antenna.gain = 3dB

#-------------- ENERRGY CONSUMPTION ----------------
*.**.wlan[0].radio.energyConsumer.typename = "StateBasedEpEnergyConsumer"
*.**.wlan[0].radio.energyConsumer.offPowerConsumption = 0mW
*.**.wlan[0].radio.energyConsumer.sleepPowerConsumption = 1mW
*.**.wlan[0].radio.energyConsumer.switchingPowerConsumption = 1mW
*.**.wlan[0].radio.energyConsumer.receiverIdlePowerConsumption = 2mW
*.**.wlan[0].radio.energyConsumer.receiverBusyPowerConsumption = 5mW
*.**.wlan[0].radio.energyConsumer.receiverReceivingPowerConsumption = 10mW
*.**.wlan[0].radio.energyConsumer.transmitterIdlePowerConsumption = 2mW
*.**.wlan[0].radio.energyConsumer.transmitterTransmittingPowerConsumption = 100mW

*.**.energyStorage.typename = "IdealEpEnergyStorage"

*.**.wlan[0].radio.displayInterferenceRange = false

# ---------------------- ΟΠΤΙΚΟΠΟΙΗΣΗ (ANIMATIONS) ----------------------
*.visualizer.typename = "IntegratedCanvasVisualizer"
*.visualizer.signalVisualizer.typename = "SignalCanvasVisualizer"
*.visualizer.mediumVisualizer.displaySignals = true
*.visualizer.packetDropVisualizer.typename = "PacketDropCanvasVisualizer"
*.visualizer.communicationRangeVisualizer.typename = "CommunicationRangeCanvasVisualizer"
*.**.wlan[0].radio.displayCommunicationRange = true
*.visualizer.physicalLinkVisualizer.packetFilter = "UDPData*"

*.visualizer.mobilityVisualizer.typename = "MobilityCanvasVisualizer"
*.visualizer.mobilityVisualizer.displayMovementTrails = true
*.visualizer.networkRouteVisualizer.displayRoutes = true
*.visualizer.dataLinkVisualizer.packetFilter = "AODV*"


[Config General1]
description = General 1 basic scenario with drones
extends = General 

# ---------------------- ΔΙΑΚΙΝΗΣΗ ΔΕΔΟΜΕΝΩΝ ----------------------
*.BuildingA.numApps = 1
*.BuildingA.app[0].typename = "UdpBasicApp"
*.BuildingA.app[0].destAddresses = "BuildingB"
*.BuildingA.app[0].messageLength = 1000B  
*.BuildingA.app[0].sendInterval = 1s
*.BuildingA.app[0].destPort = 5000

*.BuildingB.numApps = 1
*.BuildingB.app[0].typename = "UdpSink"
*.BuildingB.app[0].localPort = 5000

*.**.app[0].packetSent.vector-recording = true
*.**.app[0].packetSent.scalar-recording = true
*.**.app[0].packetReceived.scalar-recording = true
*.**.app[0].packetReceived.vector-recording = true


# ---------------------- ΚΙΝΗΣΗ DRONES ----------------------
*.drone*.mobility.typename = "LinearMobility"

*.drone*.mobility.speed = 10mps

*.drone*.mobility.initialZ = 50m

*.drone1.mobility.constraintAreaMinX = 410m   
*.drone1.mobility.constraintAreaMaxX = 700m 

*.drone2.mobility.constraintAreaMinX = 500m   
*.drone2.mobility.constraintAreaMaxX = 800m 

*.drone3.mobility.constraintAreaMinX = 750m   
*.drone3.mobility.constraintAreaMaxX = 1010m 
 
*.drone4.mobility.constraintAreaMinX = 970m   
*.drone4.mobility.constraintAreaMaxX = 1250m 

*.drone5.mobility.constraintAreaMinX = 1350m   
*.drone5.mobility.constraintAreaMaxX = 1550m 

*.drone*.mobility.constraintAreaMinY = 400m   
*.drone*.mobility.constraintAreaMaxY = 800m 

*.drone1.mobility.initialMovementHeading = uniform(230deg, 300deg)  
*.drone2.mobility.initialMovementHeading = uniform(230deg, 300deg)  
*.drone3.mobility.initialMovementHeading = uniform(230deg, 300deg) 
*.drone4.mobility.initialMovementHeading = uniform(230deg, 300deg)
*.drone5.mobility.initialMovementHeading = uniform(230deg, 300deg)

*.drone*.mobility.vector-recording = true

# ----------------- ΧΡΗΣΗ AODV ΩΣ ΠΡΩΤΟΚΟΛΛΟ ΔΡΟΜΟΛΟΓΗΣΗΣ ----------
*.**.routingTable.typename = "AodvRouting"
*.*.routingApp.typename = "Aodv"
*.Building*.typename = "AodvRouter"
*.drone*.typename = "AodvRouter"

#----------------------- ΠΡΟΣΘΗΚΗ DRONES ---------------------
[Config General1Scenario1a]
description = Adding a drone
extends = General1
network = ThesisB

*.drone1.mobility.constraintAreaMinX = 350m   
*.drone1.mobility.constraintAreaMaxX = 550m 

*.drone2.mobility.constraintAreaMinX = 550m   
*.drone2.mobility.constraintAreaMaxX = 800m 

*.drone3.mobility.constraintAreaMinX = 600m   
*.drone3.mobility.constraintAreaMaxX = 950m 
 
*.drone4.mobility.constraintAreaMinX = 1100m   
*.drone4.mobility.constraintAreaMaxX = 1300m 

*.drone5.mobility.constraintAreaMinX = 900m   
*.drone5.mobility.constraintAreaMaxX = 1200m 

*.drone6.mobility.constraintAreaMinX = 1350m   
*.drone6.mobility.constraintAreaMaxX = 1550m 

*.drone*.mobility.constraintAreaMinY = 400m   
*.drone*.mobility.constraintAreaMaxY = 800m 


*.drone6.mobility.initialMovementHeading = uniform(230deg, 300deg)

#--------------------- ΠΡΟΣΘΗΚΗ DRONES ----------------------
[Config General1Scenario1b]
description = Adding another drone 
extends = General1Scenario1a
network = ThesisC

*.drone1.mobility.constraintAreaMinX = 350m   
*.drone1.mobility.constraintAreaMaxX = 550m 

*.drone2.mobility.constraintAreaMinX = 600m   
*.drone2.mobility.constraintAreaMaxX = 870m 

*.drone3.mobility.constraintAreaMinX = 600m   
*.drone3.mobility.constraintAreaMaxX = 800m 
 
*.drone4.mobility.constraintAreaMinX = 800m   
*.drone4.mobility.constraintAreaMaxX = 1100m 

*.drone5.mobility.constraintAreaMinX = 950m   
*.drone5.mobility.constraintAreaMaxX = 1250m 

*.drone6.mobility.constraintAreaMinX = 1150m   
*.drone6.mobility.constraintAreaMaxX = 1350m 

*.drone7.mobility.constraintAreaMinX = 1400m   
*.drone7.mobility.constraintAreaMaxX = 1590m

*.drone*.mobility.constraintAreaMinY = 400m   
*.drone*.mobility.constraintAreaMaxY = 800m 

*.drone6.mobility.initialMovementHeading = uniform(230deg, 300deg)
*.drone7.mobility.initialMovementHeading = uniform(270deg, 300deg)

#------------------- ΑΛΛΑΓΗ ΤΑΧΥΤΗΤΑΣ ----------------------
[Config General1Scenario2a]
description = increasing speed to 15mps
extends = General1Scenario1b

*.drone*.mobility.speed=15mps 

#----------------- ΑΛΛΑΓΗ ΤΑΧΥΤΗΤΑΣ -----------------------
[Config General1Scenario2b]
description = increasing speed to 20mps
extends = General1Scenario1b

*.drone*.mobility.speed=20mps 

#---------------- ΑΛΛΑΓΗ ΤΑΧΥΤΗΤΑΣ ------------------------
[Config General1Scenario2c]
description = decreasing speed to 7mps
extends = General1Scenario1b

*.drone*.mobility.speed=7mps 

#---------------- ΑΛΛΑΓΗ ΤΑΧΥΤΗΤΑΣ ------------------------
[Config General1Scenario2d]
description = decreasing speed to 5mps 
extends = General1Scenario1b

*.drone*.mobility.speed=5mps 

#--------------- ΑΛΛΑΓΗ ΠΡΩΤΟΚΟΛΛΟΥ ΔΡΟΜΟΛΟΓΗΣ ------------
[Config General1Scenario3a]
description = Dsdv
extends = General1Scenario2d

*.**.routingTable.typename = "DsdvRouting"
*.*.routingApp.typename = "Dsdv"
*.Building*.typename = "DsdvRouter"
*.drone*.typename = "DsdvRouter"

#-------------- ΑΛΛΑΓΗ ΠΡΩΤΟΚΟΛΛΟΥ ΔΡΟΜΟΛΟΓΗΣΗΣ -----------
[Config General1Scenario3b]
description = Gpsr 
extends = General1Scenario2d

*.*.routing.typename = "Gpsr"
*.Building*.typename = "GpsrRouter"
*.drone*.typename = "GpsrRouter"

**.planarizationMode = "RNG"
**.displayBubbles = true

*.**.gpsr.maxJitter = 0.1s

#-------------- ΑΛΛΑΓΗ MOBILITY MODULE -----------
[Config General1Scenario4a]
description = Changing to Massmobility 
extends = General1Scenario2d

*.drone*.mobility.typename = "MassMobility"
*.drone*.mobility.initFromDisplayString =  true
*.drone*.mobility.changeInterval = truncnormal(2s, 0.5s)
*.drone*.mobility.angleDelta = normal(0deg, 30deg)
*.drone*.mobility.speed = truncnormal(15mps, 10mps)
*.drone*.mobility.updateInterval = 100ms

#----------- MASSMOBILITY WITH DSDV ----------------
[Config General1Scenario4b]
description= Massmobility with Dsdv
extends = General1Scenario3a

*.drone*.mobility.typename = "MassMobility"
*.drone*.mobility.initFromDisplayString =  true
*.drone*.mobility.changeInterval = truncnormal(2s, 0.5s)
*.drone*.mobility.angleDelta = normal(0deg, 30deg)
*.drone*.mobility.speed = truncnormal(15mps, 10mps)
*.drone*.mobility.updateInterval = 100ms

#----------- MASSMOBILITY WITH GPSR ----------------
[Config General1Scenario4c]
description = Massmobility with GPSR
extends = General1Scenario3b

*.drone*.mobility.typename = "MassMobility"
*.drone*.mobility.initFromDisplayString =  true
*.drone*.mobility.changeInterval = truncnormal(2s, 0.5s)
*.drone*.mobility.angleDelta = normal(0deg, 30deg)
*.drone*.mobility.speed = truncnormal(15mps, 10mps)
*.drone*.mobility.updateInterval = 100ms

#-------------- SCENARIO MANAGER WITH AODV--------------------
[Config General1Scenario5a]
description = Using Scenario Manager
extends = General1Scenario2d

*.scenarioManager.script = xmldoc("scenarioManager.xml")

*.drone*.hasStatus = true
*.drone*.status.initialStatus = "up"

#-------------- SCENARIO MANAGER WITH DSDV--------------------
[Config General1Scenario5b]
description = Using Scenario Manager
extends = General1Scenario3a

*.scenarioManager.script = xmldoc("scenarioManager.xml")

*.drone*.hasStatus = true
*.drone*.status.initialStatus = "up"

#-------------- SCENARIO MANAGER WITH GPSR -------------------
[Config General1Scenario5c]
description = Using Scenario Manager
extends = General1Scenario3b

*.scenarioManager.script = xmldoc("scenarioManager.xml")

*.drone*.hasStatus = true
*.drone*.status.initialStatus = "up"

#-------------- SCENARIO WITH CARS AND MORE BUILDINGS -------------------
[Config General2]
description = Using Cars instead of Drones 
extends = General
network = ThesisD 

*.BuildingA.numApps = 1
*.BuildingA.app[0].typename = "UdpBasicApp"
*.BuildingA.app[0].destAddresses = "BuildingE"
*.BuildingA.app[0].messageLength = 1000B  
*.BuildingA.app[0].sendInterval = 1s
*.BuildingA.app[0].destPort = 5000

*.BuildingE.numApps = 1
*.BuildingE.app[0].typename = "UdpSink"
*.BuildingE.app[0].localPort = 5000

# ---------------------- ΕΜΒΕΛΕΙΑ ΣΗΜΑΤΩΝ ----------------------
*.Building*.wlan[0].radio.transmitter.power = 2mW

*.car*.wlan[0].radio.transmitter.power = 1.3mW

# ---------- ΧΡΗΣΗ AODV ΩΣ ΠΡΩΤΟΚΟΛΛΟ ΔΡΟΜΟΛΟΓΗΣΗΣ -------------
*.**.routingTable.typename = "AodvRouting"
*.*.routingApp.typename = "Aodv"
*.Building*.typename = "AodvRouter"
*.car*.typename = "AodvRouter"

*.**.aodv.helloInterval = 0.5s
*.**.aodv.activeRouteTimeout = 1.5s
*.**.aodv.allowedHelloLoss = 1

#----------------- ΚΙΝΗΣΗ ΑΥΤΟΚΙΝΗΤΩΝ ----------------------
*.visualizer.mobilityVisualizer.displayMobility = true
*.environment.ground.typename = "FlatGround"

*.car*.mobility.typename = "VehicleMobility"
*.car*.mobility.waypointProximity = 3m
*.car*.mobility.speed = uniform(20mps,40mps)
*.car*.mobility.groundModule = "environment.ground"

*.car*.mobility.updateInterval = 0.05s

*.car1.mobility.waypointFile = "car1.txt"
*.car2.mobility.waypointFile = "car2.txt"
*.car3.mobility.waypointFile = "car3.txt"
*.car4.mobility.waypointFile = "car4.txt"
*.car5.mobility.waypointFile = "car5.txt"
*.car6.mobility.waypointFile = "car6.txt"
*.car7.mobility.waypointFile = "car7.txt"
*.car8.mobility.waypointFile = "car8.txt"


#------------------ ADDING MORE CARS ----------------
[Config General2Scenario1]
description = Adding more cars 
extends = General2
network = ThesisE

*.car9.mobility.waypointFile = "car9.txt"
*.car10.mobility.waypointFile = "car10.txt"
*.car11.mobility.waypointFile = "car11.txt"
*.car12.mobility.waypointFile = "car12.txt"


#--------------- ΑΛΛΑΓΗ ΠΡΩΤΟΚΟΛΛΟΥ ΔΡΟΜΟΛΟΓΗΣ ------------
[Config General2Scenario2a]
description = Dsdv with cars
extends = General2Scenario1

*.**.routingTable.typename = "DsdvRouting"
*.*.routingApp.typename = "Dsdv"
*.Building*.typename = "DsdvRouter"
*.car*.typename = "DsdvRouter"

*.**.dsdv.helloInterval = 0.5s
*.**.dsdv.routeLifetime = 5s


#-------------- ΑΛΛΑΓΗ ΠΡΩΤΟΚΟΛΛΟΥ ΔΡΟΜΟΛΟΓΗΣΗΣ -----------
[Config General2Scenario2b]
description = Gpsr with cars
extends = General2Scenario1

*.*.routing.typename = "Gpsr"
*.Building*.typename = "GpsrRouter"
*.car*.typename = "GpsrRouter"

#**.planarizationMode = "RNG"
**.displayBubbles = true

#*.**.gpsr.maxJitter = 0.1s

*.**.gpsr.beaconInterval = 0.5s
*.**.gpsr.planarizationMode = "GG"
*.**.gpsr.maxJitter = 0.15s




